# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Edson Araújo

description: Blog pessoal sobre alguns hobbies envolvendo programação.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://edsonlead.com" # the base hostname & protocol for your site, e.g. http://example.com

#Author Settings
author: Edson Araújo
about-author: Bacharel em Sistemas de Informação. Atualmente, cursa Doutorado em Biotecnologia.
author-img: logo-3.jpg
twitter: edsonlead
facebook: earaujo.dev
instagram: earaujo.py
github: edsonlead
linkedin: edson-araújo-81b10434
email: edsonlead@gmail.com

#Disqus
discus-identifier: earaujo

#Tracker
analytics: UA-64489934-1

# Build settings
markdown: kramdown
theme: flexible
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
